### ISSUE TITLE
Data Checklist

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/nl2flow#70]
Each data point must contain:

## Training

+ [x] Data hash
+ [x] NL Description
+ [x] Seed data 
+ [x] PDDL
+ [x] Plan
+ [x] Tags #69 

## Testing

+ [x] Data hash
+ [x] NL Description
+ [x] Seed data 
+ [x] PDDL
+ [x] Tags #69 

## Report

+ [x] Testing Data Instance (above)
+ [x] Model response
+ [x] Parsed model response
+ [x] Report [[schema](https://github.com/IBM/nl2flow/blob/c73072681f63ca0aa1ad61fbbfd333676d9d4001/nl2flow/debug/schemas.py#L24)] [[tests](https://github.com/IBM/nl2flow/blob/c73072681f63ca0aa1ad61fbbfd333676d9d4001/tests/debugger/test_debugger_from_flow.py#L13)]
  + [x] Soundness check 
  + [x] Validity check 
  + [x] Optimality check

**Comment by TathagataChakraborti** [comment]
Complete! 🏁
